owner: Aspect102
repo: bts-status

sites:
  - name: Website
    url: https://www.bts-crew.com/
  - name: Wiki
    url: https://wiki.bts-crew.com/
  - name: Nextcloud
    url: https://nextcloud.bts-crew.com/
  - name: Dress Notes
    url: https://bts-dressnotes.su.bath.ac.uk/
  - name: PAT Database
    url: https://assets.bts-crew.com/
  - name: Internal DNS
    url: https://dnsadmin.bts.su.bath.ac.uk/
    expectedStatusCodes: [200, 302, 301, 403]
  - name: Telephone Management
    url: https://telephony.bts-crew.com/
    expectedStatusCodes: [200, 302, 301, 403]
  - name: Access Control Admin
    url: https://auth.bts-crew.com/admin/prod/console
  - name: Access Control Admin (onprem)
    url: https://bts-auth.su.bath.ac.uk/admin/bts-prod/console
  - name: PC Deployment
    url: https://pc-deployment.bts-crew.com/
  - name: Virtual Machine Console
    url: https://incus-admin.su.bath.ac.uk/
    expectedStatusCodes: [200, 302, 301, 403]
  - name: Traefik Dashboard
    url: https://dashboard.traefik.su-srv-01.bath.ac.uk/
  - name: LibreNMS
    url: https://librenms.bts-crew.com/
  - name: Grafana
    url: https://bts-metrics.su.bath.ac.uk/
  - name: Prometheus
    url: https://bts-prom.su.bath.ac.uk/
    expectedStatusCodes: [200, 302, 301, 403]
  - name: Mimir
    url: https://bts-mimir.su.bath.ac.uk/
    expectedStatusCodes: [200, 302, 301, 403]
  - name: Alloy
    url: https://bts-alloy.su.bath.ac.uk/

  # Handset Monitoring
  - name: "Handset 101"
    url: https://bts-metrics.su.bath.ac.uk/api/prometheus/grafana/api/v1/rules
    method: GET
    headers:
      - "Authorization: Bearer $GRAFANA_TOKEN"
    __dangerous__body_down_if_text_missing: '"resource":"101","tech":"PJSIP"},"annotations":{},"state":"Normal"'
    skipNotifications: true
  - name: "Handset 102"
    url: https://bts-metrics.su.bath.ac.uk/api/prometheus/grafana/api/v1/rules
    method: GET
    headers:
      - "Authorization: Bearer $GRAFANA_TOKEN"
    __dangerous__body_down_if_text_missing: '"resource":"102","tech":"PJSIP"},"annotations":{},"state":"Normal"'
    skipNotifications: true
  - name: "Handset 103"
    url: https://bts-metrics.su.bath.ac.uk/api/prometheus/grafana/api/v1/rules
    method: GET
    headers:
      - "Authorization: Bearer $GRAFANA_TOKEN"
    __dangerous__body_down_if_text_missing: '"resource":"103","tech":"PJSIP"},"annotations":{},"state":"Normal"'
    skipNotifications: true
  - name: "Handset 111"
    url: https://bts-metrics.su.bath.ac.uk/api/prometheus/grafana/api/v1/rules
    method: GET
    headers:
      - "Authorization: Bearer $GRAFANA_TOKEN"
    __dangerous__body_down_if_text_missing: '"resource":"111","tech":"PJSIP"},"annotations":{},"state":"Normal"'
    skipNotifications: true
  - name: "Handset 112"
    url: https://bts-metrics.su.bath.ac.uk/api/prometheus/grafana/api/v1/rules
    method: GET
    headers:
      - "Authorization: Bearer $GRAFANA_TOKEN"
    __dangerous__body_down_if_text_missing: '"resource":"112","tech":"PJSIP"},"annotations":{},"state":"Normal"'
    skipNotifications: true
  - name: "Handset 113"
    url: https://bts-metrics.su.bath.ac.uk/api/prometheus/grafana/api/v1/rules
    method: GET
    headers:
      - "Authorization: Bearer $GRAFANA_TOKEN"
    __dangerous__body_down_if_text_missing: '"resource":"113","tech":"PJSIP"},"annotations":{},"state":"Normal"'
    skipNotifications: true
  - name: "Handset 114"
    url: https://bts-metrics.su.bath.ac.uk/api/prometheus/grafana/api/v1/rules
    method: GET
    headers:
      - "Authorization: Bearer $GRAFANA_TOKEN"
    __dangerous__body_down_if_text_missing: '"resource":"114","tech":"PJSIP"},"annotations":{},"state":"Normal"'
    skipNotifications: true
  - name: "Handset 115"
    url: https://bts-metrics.su.bath.ac.uk/api/prometheus/grafana/api/v1/rules
    method: GET
    headers:
      - "Authorization: Bearer $GRAFANA_TOKEN"
    __dangerous__body_down_if_text_missing: '"resource":"115","tech":"PJSIP"},"annotations":{},"state":"Normal"'
    skipNotifications: true
status-website:
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/Aspect102/bts-status/refs/heads/master/assets/bts.svg
  name: BTS Status Page
  introTitle: "This is the Backstage Technical Services status page."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
