# Change these first
owner: Aspect102 # Your GitHub organization or username, where this repository lives
repo: bts-status # The name of this repository

sites:
  - name: Website
    url: https://www.bts-crew.com/
  - name: Wiki
    url: https://wiki.bts-crew.com/
  - name: Nextcloud
    url: https://nextcloud.bts-crew.com/
  - name: Dress Notes
    url: https://bts-dressnotes.su.bath.ac.uk/
  - name: PAT Database
    url: https://assets.bts-crew.com/
  - name: Internal DNS
    url: https://dnsadmin.bts.su.bath.ac.uk/
    expectedStatusCodes:
    - 200
    - 302
    - 301
    - 403
  - name: Telephone Management
    url: https://telephony.bts-crew.com/
    expectedStatusCodes:
    - 200
    - 302
    - 301
    - 403
  - name: Access Control Admin
    url: https://auth.bts-crew.com/admin/prod/console
  - name: Access Control Admin (onprem)
    url: https://bts-auth.su.bath.ac.uk/admin/bts-prod/console
  - name: PC Deployment
    url: https://pc-deployment.bts-crew.com/
  - name: Virtual Machine Console
    url: https://incus-admin.su.bath.ac.uk/
    expectedStatusCodes:
    - 200
    - 302
    - 301
    - 403
  - name: Traefik Dashboard
    url: https://dashboard.traefik.su-srv-01.bath.ac.uk/
  - name: LibreNMS
    url: https://librenms.bts-crew.com/
  - name: Grafana
    url: https://bts-metrics.su.bath.ac.uk/
  - name: Prometheus
    url: https://bts-prom.su.bath.ac.uk/
    expectedStatusCodes:
    - 200
    - 302
    - 301
    - 403
  - name: Mimir
    url: https://bts-mimir.su.bath.ac.uk/
    expectedStatusCodes:
    - 200
    - 302
    - 301
    - 403
  - name: Alloy
    url: https://bts-alloy.su.bath.ac.uk/
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: bts-gitstatus.su.bath.ac.uk
  baseUrl: /bts-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BTS Status Page
  introTitle: "This is the Backstage Technical Services status page for all of our services."
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
