name: Upptime Matrix Alerts
on:
  issues:
    types: [opened, closed]

jobs:
  matrix-notification:
    # Only run if the issue is tagged as a status alert by Upptime
    if: contains(github.event.issue.labels.*.name, 'status')
    runs-on: ubuntu-latest
    steps:
      - name: Send status to Matrix
        uses: fadenb/matrix-chat-message@v0.0.6
        with:
          homeserver: 'matrix.laserbeam31.uk' # Change if using a private server
          token: ${{ secrets.MATRIX_TOKEN }}
          channel: '!xUcaroYgJWBNZMTspq:matrix.laserbeam31.uk' # MUST be the internal Room ID
          message: |
            ### Upptime Alert: ${{ github.event.issue.title }}
            **Status:** ${{ github.event.action == 'opened' && '🟥 DOWN' || '🟩 BACK UP' }}
            **Details:** [View Incident](${{ github.event.issue.html_url }})
